// <auto-generated />
using System;
using RoboDeApostas.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RoboDeApostas.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230410190614_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoboDeApostas.Models.Liga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Liga");
                });

            modelBuilder.Entity("RoboDeApostas.Models.LinkDaLiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CasaDeAposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LigaId")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LigaId");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.ToTable("LinkDaLiga");
                });

            modelBuilder.Entity("RoboDeApostas.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCompleta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Liga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkDaPartida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeDaCasaDeAposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeTimeDaCasa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeTimeVisitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ODD_Empate_Ambos")
                        .HasColumnType("real");

                    b.Property<float>("ODD_VitoriaOuEmpate_TimeCasa")
                        .HasColumnType("real");

                    b.Property<float>("ODD_VitoriaOuEmpate_TimeVisitante")
                        .HasColumnType("real");

                    b.Property<float>("ODD_Vitoria_TimeDaCasa")
                        .HasColumnType("real");

                    b.Property<float>("ODD_Vitoria_TimeVisitante")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("RoboDeApostas.Models.Surebet2Casas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Surebet2Casas");
                });

            modelBuilder.Entity("RoboDeApostas.Models.Surebet3Casas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Surebet3Casas");
                });

            modelBuilder.Entity("RoboDeApostas.Models.LinkDaLiga", b =>
                {
                    b.HasOne("RoboDeApostas.Models.Liga", "Liga")
                        .WithMany()
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });
#pragma warning restore 612, 618
        }
    }
}
